name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install backend deps
        working-directory: ./backend
        run: npm ci

      - name: Run backend lint (optional)
        working-directory: ./backend
        run: |
          echo "No lint configured"

      - name: Install frontend deps
        working-directory: ./frontend
        run: npm ci

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Archive frontend build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist

  # Optional: add a deploy job to Render using API key (set RENDER_API_KEY secret)
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trigger Render deploy (optional)
        if: ${{ secrets.RENDER_API_KEY }}
        run: |
          echo "You can trigger Render deploy via API here. Add a curl call to Render's deploy endpoint with RENDER_SERVICE_ID and RENDER_API_KEY."
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
